version: "3.8"
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src:/var/www/html
    environment:
      - NGINX_PORT=80
    depends_on:
      - php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    env_file:
      - ./env/mysql.env
